### ISSUE TITLE
yum update fails

### ISSUE THREAD

**Issue by yrsurya** [amazonlinux/container-images#38] opened 2020-03-26 14:40 UTC
docker run -it --entrypoint /bin/bash amazonlinux:latest
Unable to find image 'amazonlinux:latest' locally
latest: Pulling from library/amazonlinux
a7583ef20c9d: Already exists 
Digest: sha256:88a720de445a49a039bf9817af06e93c95e36f438bb8d72c15fb5a9bcae86bd6
Status: Downloaded newer image for amazonlinux:latest
bash-4.2# yum update
Loaded plugins: ovl, priorities
Could not retrieve mirrorlist http://amazonlinux.default.amazonaws.com/2/core/latest/x86_64/mirror.list error was
12: Timeout on http://amazonlinux.default.amazonaws.com/2/core/latest/x86_64/mirror.list: (28, 'Resolving timed out after 5000 milliseconds')

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: amzn2-core/2/x86_64

**Comment by iliana** [comment] 2020-03-26 18:29
Does DNS work in your container? It's failing to resolve the hostname. Try `curl http://http://checkip.amazonaws.com/` in a container.

**Comment by yrsurya** [comment] 2020-03-27 14:20
not connected to vpn
(master) ~/P/B/S/d/testimage> docker run -it --entrypoint /bin/bash amazonlinux:latest
bash-4.2# curl http://checkip.amazonaws.com
68.62.191.154
bash-4.2# exit
connected to vpn
(master) ~/P/B/S/d/testimage> docker run -it --entrypoint /bin/bash amazonlinux:latest
bash-4.2# curl http://checkip.amazonaws.com
204.78.58.45

**Comment by yrsurya** [comment] 2020-03-27 14:21
So Issue am facing only when I connected to my corporate vpn , or else I am not seeing any issue

**Comment by yrsurya** [comment] 2020-05-04 02:44
seems to be seeing issue again after updating to fedora-32 even not connected to vpn 
username@host ~> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
118a59ad5f6e        bridge              bridge              local
dc031caabe73        host                host                local
eb0b520bebe3        none                null                local
username@host ~> docker run -it --entrypoint /bin/bash amazonlinux:latest
bash-4.2# curl http://checkip.amazonaws.com
curl: (6) Could not resolve host: checkip.amazonaws.com

and yum updates fails

**Comment by odidev** [comment] 2021-03-05 13:33
I was trying to add arm64 support to [mobingi/alm-awslogs](https://github.com/mobingidocker/alm-awslogs) image and it uses amazonlinux as the base image. When updated the amazonlinux image tag to the latest and tried to build the image. I was facing the below-mentioned error. So, I have pulled `amazonlinux:latest` image on my local arm64 machine and ran `yum update` in the amazonlinux container. I am getting the same issue as mentioned in this issue. Please check the below logs for more details:
```
bash-4.2# yum update
Loaded plugins: ovl, priorities
Could not retrieve mirrorlist http://amazonlinux.default.amazonaws.com/2/core/latest/aarch64/mirror.list error was
12: Timeout on http://amazonlinux.default.amazonaws.com/2/core/latest/aarch64/mirror.list: (28, 'Resolving timed out after 5000 milliseconds')


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: amzn2-core/2/aarch64

```
I have tried the same thing on the x64 machine and it is running perfectly fine.

Please provide any pointers on resolving this issue in arm64 platform.

**Comment by sreerammeka** [comment] 2022-01-31 07:38
I'm also using Amazon Linux 2 Docker base images and Amazon Linux latest docker images, still facing the same issue as  above and also SSL certificate issues.

**Comment by sktomer** [comment] 2022-04-05 21:57
Hello,

I'm from Amazon Linux team. The common theme here seems to be related to corporate VPN.
The following questions should help narrow down the issue more:
* Before you run docker, did `curl http://checkip.amazonaws.com/` succeed ?
    * If no, you probably need internet connectivity.
* If yes, does yum commands still fail inside the container with timed out errors ?
* If yes, does `curl http://checkip.amazonaws.com/` fail from within the container ?
* If yes, can you try launching a similar container image for fedora or any other linux distro and see if that works as expected ?
    * If no, maybe something is weird with the docker network configuration.

Please post results for this exercise so we can dive into this issue further. The Amazon Linux repos are definitely reachable worldwide, so this issue should be due to misconfigured network at some level. If you've already figured out the issue, please share your feedback as well.

Please re-open this issue if you still believe the issue is specific to Amazon Linux containers.

Thanks,
Sumit

**Closed by sktomer** 2022-04-05 21:57 UTC
