### ISSUE TITLE
Issues connecting to amazonlinux repo

### ISSUE THREAD

**Issue by flyingalphaunicorn** [amazonlinux/container-images#91] opened 2023-03-27 14:48 UTC
Running the following docker file statements and encountered this error for yum install, this just started recently, probably with the latest release, any thoughts ?

FROM amazonlinux:latest
RUN yum update -y
RUN yum install shadow-utils python3 python3-pip zip unzip git -y

Errors during downloading metadata for repository 'amazonlinux':
  - Curl error (6): Couldn't resolve host name for https://cdn.amazonlinux.com/al2023/core/mirrors/2023.0.20230315/x86_64/mirror.list [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'amazonlinux': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://cdn.amazonlinux.com/al2023/core/mirrors/2023.0.20230315/x86_64/mirror.list [getaddrinfo() thread failed to start]
Ignoring repositories: amazonlinux

**Comment by mysteriouspants** [comment] 2023-03-27 17:44
This may also be an instance of a security policy that needs to be updated. See https://github.com/amazonlinux/amazon-linux-2023/issues/80#issuecomment-1017798237 for details.

**Comment by royalcala** [comment] 2023-03-29 23:45
same here, works with a previous version for example with amazonlinux:2 but with the latest now is not working, my config is the next using buildkite

  - docker#v5.6.0:
        image: "amazonlinux:latest"
        always-pull: true

errors:
Unable to find image 'amazonlinux:latest' locally
--
  | latest: Pulling from library/amazonlinux
  | ee5c3b4d09bc: Pull complete
  | Digest: sha256:1293fb4fa103ea81a8769d7b0aa000072884b0750c0a28563fd9838fea784245
  | Status: Downloaded newer image for amazonlinux:latest
  | Amazon Linux 2023 repository                    0.0  B/s \|   0  B     00:00
  | Errors during downloading metadata for repository 'amazonlinux':
  | - Curl error (6): Couldn't resolve host name for https://cdn.amazonlinux.com/al2023/core/mirrors/2023.0.20230322/x86_64/mirror.list [getaddrinfo() thread failed to start]
  | Error: Failed to download metadata for repo 'amazonlinux': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://cdn.amazonlinux.com/al2023/core/mirrors/2023.0.20230322/x86_64/mirror.list [getaddrinfo() thread failed to start]
  | Ignoring repositories: amazonlinux
  | No match for argument: unzip

**Comment by sktomer** [comment] 2023-03-31 23:01
Few questions to understand the issue better:
* What is the docker version you're using (`docker -v`) as well as what machine/server are you running this from ?
* Does `curl https://cdn.amazonlinux.com/al2023/core/mirrors/2023.0.20230322/x86_64/mirror.list` work directly from the host ?
* Do you still see the issue if you run using docker version >= 20.x ?

**Comment by nmeyerhans** [comment] 2023-04-19 16:01
@matt123test Please see https://github.com/amazonlinux/amazon-linux-2023/issues/80#issuecomment-1017798237.  This is not an issue that can be addressed in the Amazon Linux container images. The issue is with the Docker version you're running, and the remedy is to update Docker.

**Closed** 2023-04-19 18:19 UTC
